name: Validate Data

on:
  pull_request:
    paths:
      - 'Fixtures/**.json'  # Adjust the path to your data files

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version you need

      - name: Install dependencies
        run: pip install jsonschema  # Add any dependencies you need

      - name: Validate data
        run: python validate_data.py path/to/your/data.json